sudo: false
language: node_js
node_js:
  - "8.1.2"
env:
  global:
    - export NODE_ENV=development

before_script:
  - npm install -g gulp-cli
  - npm install --save-dev gulp
script:
  - gulp
after_success:
  - rm -rf coverage/